### ISSUE TITLE
Auto Animate Magic Motion not working!

### ISSUE THREAD

**Issue by ammein** [tisho/Switch.framerfx#13]
The new update Framer Web causes Switch Auto Animate Magic Motion not working. Can you fix this immediately?

You can try the behaviour on Switch Examples at **Toggle** sample.

**Comment by tisho** [comment]
Sorry for the overdue reply. I believe this issue was fixed with the Oct 17 update (1.27.0), and there was another breaking change that was fixed in 1.28.0. I'm going to close this for now, but if you see more issues, let me know.
