### ISSUE TITLE
With AutoAnimate, visibility of an instance is not updated

### ISSUE THREAD

**Issue by davidhoeller** [tisho/Switch.framerfx#4]
Visibility of child instances is not "auto animated". If I should provide an example, just let me know.

**Comment by tisho** [comment]
Good catch. Would you expect visibility to update through an opacity transition?

**Comment by davidhoeller** [comment]
Just reading it's fixed – thanks @tisho! 
(Answering to your question: yes, but a "hard" visibility switch would also be ok of course. :-))

**Comment by tisho** [comment]
As I was implementing the fix I realized that it would be better to treat layers that were hidden from the layer panel as exiting elements, so for now it just picks up the exit transition (a fade out by default). It won’t try to animate position or anything like that. Hopefully this does the job.
